'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { usePathname, useRouter, useSearchParams } from 'next/navigation';
import { ArrowUpRight, Heart, Menu, Search, ShoppingBag, Plus, Minus, SlidersHorizontal, Trash2, Smartphone, User, ChevronDown } from 'lucide-react';
import { money, type Product } from '@/lib/catalog';
import { colorValue, emptyFilters, filterProducts, isCompatible, productHref, type ShopFilters } from '@/lib/storefront-policy';
import { useStore } from './store-provider';
import { CatalogStatus, DeviceSelector, Modal, ProductPhoto } from './commerce-ui';
const links = [['Cases', '/shop?category=CASE'], ['Accesorios', '/accessories'], ['Tecnología', '/smart'], ['Personaliza', '/custom'], ['Colecciones', '/drops'], ['Ofertas', '/shop?offers=1']];
export function Nav() {
    const [menu, setMenu] = useState(false), [mega, setMega] = useState(false), [search, setSearch] = useState(false), [device, setDevice] = useState(false);
    const { cart, setCartOpen, devices, selectedDeviceId } = useStore();
    const pathname = usePathname();
    const selected = devices.find(d => d.id === selectedDeviceId);
    const count = cart.reduce((n, i) => n + i.qty, 0);
    useEffect(() => { setMenu(false); setMega(false); setSearch(false); setDevice(false); }, [pathname]);
    return <><a href="#main-content" className="skip-link">Ir al contenido</a><div className="promo-bar">ALTER YOUR PHONE. <span>Protección · Tecnología · Tu estilo</span></div><header className="site-nav"><Link href="/" className="brand-logo" aria-label="ALTER-CASE inicio">ALTER<span>/</span>CASE<sup>®</sup></Link><nav className="desktop-nav" aria-label="Navegación principal"><button className="nav-link" aria-expanded={mega} aria-controls="mega-menu" onClick={() => setMega(!mega)}>Cases <ChevronDown size={13}/></button>{links.slice(1).map(([name, url]) => <Link key={url} href={url}>{name}</Link>)}</nav><div className="nav-actions"><button className="device-trigger" onClick={() => setDevice(true)} aria-label="Seleccionar dispositivo"><Smartphone size={18}/><span>{selected?.name ?? 'Mi dispositivo'}</span></button><button className="icon-button" onClick={() => setSearch(true)} aria-label="Buscar"><Search size={19}/></button><Link href="/favorites" className="icon-button nav-favorites" aria-label="Favoritos"><Heart size={18}/></Link><Link href="/account" className="icon-button nav-account" aria-label="Mi cuenta"><User size={18}/></Link><button onClick={() => setCartOpen(true)} aria-label={`Abrir carrito con ${count} productos`} className="icon-button relative"><ShoppingBag size={19}/>{count > 0 && <span className="cart-count">{count}</span>}</button><button onClick={() => setMenu(true)} className="icon-button mobile-trigger" aria-label="Abrir menú" aria-expanded={menu}><Menu size={22}/></button></div></header>{mega && <div id="mega-menu" className="mega-menu" onKeyDown={e => { if (e.key === 'Escape')
        setMega(false); }}><MegaLinks close={() => setMega(false)}/></div>}{menu && <Modal title="Explora ALTER" drawer onClose={() => setMenu(false)}><nav className="mobile-links">{links.map(([name, url]) => <Link key={url} href={url} onClick={() => setMenu(false)}>{name}<ArrowUpRight size={18}/></Link>)}<details><summary>Comprar por dispositivo</summary><DeviceSelector onDone={() => setMenu(false)}/></details><Link href="/favorites">Favoritos</Link><Link href="/account">Mi cuenta</Link></nav></Modal>}{search && <Modal title="Encuentra tu próximo ALTER" onClose={() => setSearch(false)}><SearchPanel onClose={() => setSearch(false)}/></Modal>}{device && <Modal title="¿Qué celular tienes?" onClose={() => setDevice(false)}><p className="muted">Elige tu modelo para encontrar productos compatibles.</p><DeviceSelector onDone={() => setDevice(false)}/></Modal>}<CartDrawer /></>;
}
function MegaLinks({ close }: {
    close: () => void;
}) { const { devices, products } = useStore(); const brands = Array.from(new Map(devices.map(d => [d.brand.id, d.brand])).values()); const p = products.find(p => p.image && !p.isDemo); return <><div><p className="eyebrow">POR MARCA</p>{brands.map(b => <Link onClick={close} key={b.id} href={`/shop?q=${encodeURIComponent(b.name)}`}>{b.name}</Link>)}<Link onClick={close} href="/shop">Ver todos los cases</Link></div><div><p className="eyebrow">POR TECNOLOGÍA</p>{['MAGSAFE', 'NFC', 'E_INK', 'QI2'].map(t => <Link key={t} onClick={close} href={`/shop?technology=${t}`}>{t.replace('_', '-')}</Link>)}</div><div><p className="eyebrow">EXPLORA</p><Link onClick={close} href="/shop?sort=newest">Nuevos productos</Link><Link onClick={close} href="/drops">Colecciones</Link><Link onClick={close} href="/shop?offers=1">Ofertas disponibles</Link></div>{p && <Link onClick={close} href={productHref(p)} className="mega-feature"><div className="relative aspect-square"><ProductPhoto src={p.image} alt={p.alt}/></div><b>{p.name}</b></Link>}</>; }
function SearchPanel({ onClose }: {
    onClose: () => void;
}) { const { products, devices, selectedDeviceId } = useStore(); const [query, setQuery] = useState(''), [debounced, setDebounced] = useState(''); useEffect(() => { const id = setTimeout(() => setDebounced(query), 200); return () => clearTimeout(id); }, [query]); const result = filterProducts(products, devices, { ...emptyFilters, q: debounced, device: selectedDeviceId }).slice(0, 5); return <><form action="/shop" onSubmit={onClose}><label className="search-field"><Search size={20}/><input autoFocus name="q" aria-label="Buscar productos" value={query} onChange={e => setQuery(e.target.value)} placeholder="Busca un case, modelo o color"/><button className="text-link">Buscar</button></label></form><p className="eyebrow mt-7">{query ? 'PRODUCTOS' : 'EXPLORA EL CATÁLOGO'}</p><div className="search-results" aria-live="polite">{result.map(p => <Link key={p.id} onClick={onClose} href={productHref(p)}><div className="relative h-16 w-16"><ProductPhoto src={p.image} alt={p.alt}/></div><span>{p.name}<small>{p.collection}</small></span><b>{money(p.price)}</b></Link>)}{query && !result.length && <p>No encontramos coincidencias. Prueba otro modelo o palabra.</p>}</div><div className="chip-list">{['MAGSAFE', 'NFC', 'QI2'].map(t => <Link onClick={onClose} href={`/shop?technology=${t}`} className="pill" key={t}>{t}</Link>)}</div></>; }
function CartDrawer() { const { cart, cartOpen, setCartOpen, updateCart, removeFromCart } = useStore(); if (!cartOpen)
    return null; return <Modal title={`Tu carrito · ${cart.reduce((n, i) => n + i.qty, 0)}`} drawer onClose={() => setCartOpen(false)}><div className="drawer-items">{!cart.length ? <div className="empty-state"><ShoppingBag size={32}/><h3>Tu próximo favorito está por llegar.</h3><Link onClick={() => setCartOpen(false)} href="/shop" className="button-dark">Explorar productos</Link></div> : cart.map(item => <div className="cart-item" key={item.id}><Link href={`/product/${item.slug}`} onClick={() => setCartOpen(false)} className="cart-item-photo"><ProductPhoto src={item.image} alt={item.name} sizes="80px"/></Link><div><Link href={`/product/${item.slug}`} onClick={() => setCartOpen(false)}><b>{item.name}</b></Link><p>{item.model} · {item.color}</p><div className="quantity"><button aria-label={`Reducir ${item.name}`} onClick={() => updateCart(item.id, item.qty - 1)}><Minus size={14}/></button><span>{item.qty}</span><button disabled={item.qty >= item.availableStock} aria-label={`Aumentar ${item.name}`} onClick={() => updateCart(item.id, item.qty + 1)}><Plus size={14}/></button></div></div><div className="cart-item-end"><button aria-label={`Eliminar ${item.name}`} onClick={() => removeFromCart(item.id)}><Trash2 size={17}/></button><b>{money(item.price * item.qty)}</b></div></div>)}</div>{cart.length > 0 && <div className="drawer-total"><p><span>Subtotal</span><b>{money(cart.reduce((a, i) => a + i.price * i.qty, 0))}</b></p><Link onClick={() => setCartOpen(false)} href="/checkout" className="button-dark">Continuar con mi compra</Link><small>Precio y disponibilidad se confirman al continuar.</small></div>}</Modal>; }
export function ProductCard({ p }: {
    p: Product;
}) {
    const { favorites, toggleFavorite, devices, selectedDeviceId } = useStore();
    const device = devices.find(d => d.id === selectedDeviceId);
    const available = p.variants.filter(v => isCompatible(p, v, device));
    const [selected, setSelected] = useState(''), [preview, setPreview] = useState('');
    const variant = available.find(v => v.id === (preview || selected)) ?? available[0];
    if (!variant)
        return null;
    const colors = Array.from(new Map(available.map(v => [v.color, v])).values());
    const images = p.images?.filter(i => !i.variantId || i.variantId === variant.id) ?? [];
    const primary = variant.imageUrl || images[0]?.url || p.image;
    const secondary = images.find(i => i.url !== primary && i.type === 'IMAGE');
    const href = productHref(p, variant, device);
    const liked = favorites.includes(p.id);
    return <article className="product-card"><div className="product-card-media"><Link href={href} aria-label={`Ver ${p.name}`}><ProductPhoto src={primary} alt={`${p.name} · ${variant.color}`} className="product-image"/>{secondary && <div className="product-second"><ProductPhoto src={secondary.url} alt={secondary.alt}/></div>}</Link><div className="product-badges">{p.tag && <span className="tag">{p.tag}</span>}{!variant.availableStock && <span className="tag">AGOTADO</span>}</div><button className="favorite-button" onClick={() => toggleFavorite(p.id)} aria-label={`${liked ? 'Quitar de' : 'Guardar en'} favoritos ${p.name}`} aria-pressed={liked}><Heart size={18} fill={liked ? 'currentColor' : 'none'}/></button></div><div className="card-info"><p className="eyebrow muted">{p.collection}</p><Link className="card-title" href={href}>{p.name}<ArrowUpRight size={17}/></Link><p className="card-device">{device?.name ?? (p.compatibilityMode === 'UNIVERSAL' ? 'Consulta los requisitos de tu celular' : p.models.slice(0, 2).join(' · '))}</p><div className="card-colors">{colors.slice(0, 5).map(v => <button key={v.id} title={v.color} aria-label={`Color ${v.color}`} aria-pressed={variant.color === v.color} onMouseEnter={() => setPreview(v.id)} onMouseLeave={() => setPreview('')} onFocus={() => setPreview(v.id)} onBlur={() => setPreview('')} onClick={() => { setSelected(v.id); setPreview(''); }} className={colorValue(v.color) ? 'mini-swatch' : 'color-label'} style={colorValue(v.color) ? { background: colorValue(v.color) } : undefined}>{!colorValue(v.color) && v.color}</button>)}{colors.length > 5 && <Link href={href}>+{colors.length - 5}</Link>}</div><div className="card-price"><b>{money(variant.price)}</b>{(variant.compareAtPrice ?? 0) > variant.price && <del>{money(variant.compareAtPrice!)}</del>}</div><p className="card-features">{p.features.slice(0, 3).map(f => f.replace('_', '-')).join(' · ')}</p></div></article>;
}
export function ProductGrid({ list }: {
    list: Product[];
}) { return <div className="product-grid">{list.map(p => <ProductCard p={p} key={p.id}/>)}</div>; }
export function Shop({ initialCategory = '', initialCollection = '' }: {
    initialCategory?: string;
    initialCollection?: string;
}) {
    const { products, devices, selectedDeviceId, setSelectedDeviceId, catalogLoading, catalogError } = useStore();
    const router = useRouter(), params = useSearchParams();
    const [mobile, setMobile] = useState(false);
    const filters = { ...emptyFilters, category: initialCategory, collection: initialCollection };
    for (const key of Object.keys(emptyFilters) as (keyof ShopFilters)[]) {
        if (params.has(key))
            filters[key] = params.get(key) ?? '';
    }
    if (!params.has('device'))
        filters.device = selectedDeviceId;
    const filtered = filterProducts(products, devices, filters);
    const chosen = devices.find(d => d.id === filters.device || d.slug === filters.device);
    function update(key: keyof ShopFilters, value: string) { const query = new URLSearchParams(params.toString()); if (value)
        query.set(key, value);
    else
        query.delete(key); if (key === 'device')
        setSelectedDeviceId(devices.find(d => d.id === value || d.slug === value)?.id ?? ''); router.replace(`?${query.toString()}`, { scroll: false }); }
    const field = (key: keyof ShopFilters, label: string, options: string[]) => <label key={key}>{label}<select value={filters[key]} onChange={e => update(key, e.target.value)}><option value="">Todos</option>{options.map(value => <option key={value} value={value}>{value.replace('_', '-')}</option>)}</select></label>;
    const controls = <div className="filter-controls"><label>Dispositivo<select value={chosen?.id ?? ''} onChange={e => update('device', e.target.value)}><option value="">Todos los dispositivos</option>{devices.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}</select></label>{field('category', 'Tipo', ['CASE', 'SCREEN_PROTECTOR', 'CAMERA_PROTECTOR', 'WALLET', 'CHARGER', 'POWER_BANK', 'STAND', 'STRAP', 'CHARM'])}{field('color', 'Color', Array.from(new Set(products.flatMap(p => p.variants.map(v => v.color)))))}{field('technology', 'Tecnología', Array.from(new Set(products.flatMap(p => p.features))))}{field('material', 'Material', Array.from(new Set(products.flatMap(p => p.variants.flatMap(v => v.material ? [v.material] : [])))))}{field('collection', 'Colección', Array.from(new Set(products.map(p => p.collection))))}<fieldset><legend>Precio · COP</legend><div className="price-range"><input aria-label="Precio mínimo" type="number" min="0" value={filters.min} placeholder="Desde" onChange={e => update('min', e.target.value)}/><input aria-label="Precio máximo" type="number" min="0" value={filters.max} placeholder="Hasta" onChange={e => update('max', e.target.value)}/></div></fieldset><label className="check-filter"><input type="checkbox" checked={!!filters.stock} onChange={e => update('stock', e.target.checked ? '1' : '')}/>Solo disponibles</label><label className="check-filter"><input type="checkbox" checked={!!filters.offers} onChange={e => update('offers', e.target.checked ? '1' : '')}/>Con descuento</label></div>;
    function clear() { setSelectedDeviceId(''); router.replace('?', { scroll: false }); }
    return <><Nav /><main id="main-content" className="page-shell"><div className="catalog-heading"><p className="eyebrow">DISEÑADO PARA TU DÍA A DÍA</p><h1>{initialCollection || (initialCategory === 'ACCESSORIES' ? 'Pequeños detalles.\nGrandes posibilidades.' : 'Encuentra tu ALTER.')}</h1><p className="muted">Cases y accesorios que se adaptan a ti. Empieza por tu dispositivo.</p></div><div className="catalog-toolbar"><button className="button-outline mobile-filter" onClick={() => setMobile(true)}><SlidersHorizontal size={16}/>Filtros</button><p aria-live="polite">{filtered.length} productos{chosen ? ` para ${chosen.name}` : ''}</p><label>Ordenar<select aria-label="Ordenar productos" value={filters.sort} onChange={e => update('sort', e.target.value)}><option value="recommended">Recomendados</option><option value="newest">Más nuevos</option><option value="price-asc">Precio menor</option><option value="price-desc">Precio mayor</option></select></label></div><div className="chip-list">{(Object.keys(filters) as (keyof ShopFilters)[]).filter(key => filters[key] && key !== 'sort').map(key => <button className="filter-chip" key={key} onClick={() => update(key, '')}>{key === 'device' ? chosen?.name ?? filters[key] : key === 'stock' ? 'Disponibles' : key === 'offers' ? 'Con descuento' : key === 'min' ? `Desde ${money(Number(filters[key]))}` : key === 'max' ? `Hasta ${money(Number(filters[key]))}` : filters[key]} ×</button>)}<button className="text-link" onClick={clear}>Limpiar filtros</button></div><div className="catalog-layout"><aside className="desktop-filters"><h2>Filtrar por</h2>{controls}</aside><div><CatalogStatus />{!catalogLoading && !catalogError && (filtered.length ? <ProductGrid list={filtered}/> : <div className="empty-state"><h2>No encontramos productos compatibles.</h2><p>Prueba cambiando los filtros o tu dispositivo.</p><button className="button-dark" onClick={clear}>Limpiar filtros</button></div>)}</div></div>{mobile && <Modal title="Filtra tu selección" drawer onClose={() => setMobile(false)}>{controls}<button className="button-dark mt-6" onClick={() => setMobile(false)}>Ver {filtered.length} productos</button></Modal>}</main><Footer /></>;
}
export function Footer() { return <footer className="footer"><div className="footer-brand"><Link href="/" className="brand-logo">ALTER<span>/</span>CASE</Link><p>Protección. Tecnología.<br />Tu forma de ser.</p></div><div><h2>Comprar</h2><Link href="/shop?category=CASE">Cases</Link><Link href="/shop?technology=MAGSAFE">MagSafe</Link><Link href="/accessories">Accesorios</Link><Link href="/custom">Personalización</Link></div><div><h2>Tu ALTER</h2><Link href="/account">Mi cuenta</Link><Link href="/favorites">Favoritos</Link><Link href="/cart">Mi carrito</Link><Link href="/drops">Colecciones</Link></div><div><h2>Descubre</h2><Link href="/smart">Tecnología ALTER</Link><Link href="/shop">Compatibilidad</Link><p>Cali, Colombia</p></div><div className="footer-bottom"><span>© {new Date().getFullYear()} ALTER-CASE</span><span>ALTER YOUR PHONE.</span></div></footer>; }
