'use client';
import Image from 'next/image';
import Link from 'next/link';
import {useState} from 'react';
import {AnimatePresence,motion} from 'framer-motion';
import {ArrowUpRight,Heart,Menu,Search,ShoppingBag,X,Plus,Minus,SlidersHorizontal,Trash2} from 'lucide-react';
import {money,Product} from '@/lib/catalog';
import {useStore} from './store-provider';

export function Nav(){
  const [menu,setMenu]=useState(false);const {cart,setCartOpen}=useStore();const count=cart.reduce((n,i)=>n+i.qty,0);
  return <><header className="site-nav"><Link href="/" className="font-display text-lg tracking-tighter">ALTER / CASE</Link><nav className="hidden gap-7 text-xs tracking-[.14em] md:flex"><Link href="/shop">TIENDA</Link><Link href="/drops">COLECCIONES</Link><Link href="/smart">SMART</Link><Link href="/custom">PERSONALIZA</Link></nav><div className="flex items-center gap-4"><Link href="/favorites" aria-label="Favoritos"><Heart size={18}/></Link><button onClick={()=>setCartOpen(true)} aria-label={`Abrir carrito con ${count} productos`} className="relative"><ShoppingBag size={19}/>{count>0&&<span className="cart-count">{count}</span>}</button><button onClick={()=>setMenu(!menu)} className="md:hidden" aria-label="Menú"><Menu size={20}/></button></div></header>{menu&&<nav className="mobile-menu"><Link href="/shop">TIENDA</Link><Link href="/drops">COLECCIONES</Link><Link href="/smart">SMART</Link><Link href="/custom">PERSONALIZA</Link><Link href="/admin">ADMINISTRAR</Link></nav>}<CartDrawer/></>;
}

function CartDrawer(){
  const {cart,cartOpen,setCartOpen,updateCart,removeFromCart}=useStore();const total=cart.reduce((a,i)=>a+i.price*i.qty,0);
  return <AnimatePresence>{cartOpen&&<><motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setCartOpen(false)} className="fixed inset-0 z-50 bg-black/55"/><motion.aside initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}} transition={{type:'spring',damping:28,stiffness:260}} className="cart-drawer"><div className="flex items-center justify-between border-b border-black/10 pb-5"><div><p className="eyebrow text-clay">TU SELECCIÓN</p><b className="font-display text-2xl">CARRITO / {cart.reduce((n,i)=>n+i.qty,0)}</b></div><button onClick={()=>setCartOpen(false)} aria-label="Cerrar"><X/></button></div><div className="flex-1 overflow-auto py-4">{cart.length===0?<div className="grid h-full place-items-center text-center text-sm text-black/55">Tu carrito está vacío.<br/>Descubre una pieza que hable de ti.</div>:cart.map(item=><div className="grid grid-cols-[76px_1fr] gap-4 border-b border-black/10 py-4" key={item.id}><div className="relative h-24 overflow-hidden bg-stone"><Image src={item.image} alt={item.name} fill className="object-cover" sizes="76px"/></div><div><div className="flex justify-between gap-3"><b className="text-sm">{item.name}</b><button onClick={()=>removeFromCart(item.id)} aria-label="Eliminar"><Trash2 size={15}/></button></div><p className="mt-1 text-xs text-black/50">{item.model} · {item.color}</p><div className="mt-3 flex items-center justify-between"><div className="flex items-center border border-black/15"><button onClick={()=>updateCart(item.id,item.qty-1)} className="p-2"><Minus size={12}/></button><span className="min-w-7 text-center text-xs">{item.qty}</span><button onClick={()=>updateCart(item.id,item.qty+1)} className="p-2"><Plus size={12}/></button></div><span className="text-sm font-semibold">{money(item.price*item.qty)}</span></div></div></div>)}</div><div className="border-t border-black/15 pt-5"><div className="mb-4 flex justify-between font-bold"><span>SUBTOTAL</span><span>{money(total)}</span></div><Link onClick={()=>setCartOpen(false)} href={cart.length?'/checkout':'/shop'} className="button-dark block text-center">{cart.length?'FINALIZAR COMPRA':'IR A LA TIENDA'}</Link><p className="mt-3 text-center text-[10px] text-black/45">Envío calculado al finalizar · Compra segura</p></div></motion.aside></>}</AnimatePresence>;
}

export function ProductCard({p}:{p:Product}){
  const [liked,setLiked]=useState(false);
  return <article className="product-card group relative"><Link href={`/product/${p.slug}`}><div className="relative aspect-[.84] overflow-hidden bg-stone"><Image src={p.image} alt={p.alt} fill sizes="(max-width: 768px) 50vw, 25vw" className="product-image object-cover"/><div className="absolute left-3 top-3 flex gap-1">{p.tag&&<span className="tag">{p.tag}</span>}{p.stock===0&&<span className="tag bg-charcoal text-ivory">AGOTADO</span>}</div><span className="absolute bottom-3 right-3 flex h-9 w-9 items-center justify-center rounded-full bg-ivory text-charcoal opacity-0 transition group-hover:opacity-100"><ArrowUpRight size={17}/></span></div></Link><button onClick={()=>setLiked(!liked)} className="absolute right-2 top-2 z-10 rounded-full bg-ivory/90 p-2 text-charcoal" aria-label="Favorito"><Heart size={16} fill={liked?'currentColor':'none'}/></button><div className="pt-3"><div className="eyebrow text-muted">{p.collection} / {p.design}</div><div className="mt-1 flex items-start justify-between gap-4"><Link href={`/product/${p.slug}`} className="text-sm font-bold">{p.name}</Link><span className="whitespace-nowrap text-sm font-semibold">{money(p.price)}</span></div><div className="mt-1 flex items-center justify-between text-[11px] text-muted"><span>{p.color} · {p.stock?`${p.stock} disponibles`:'Sin existencias'}</span><Link href={`/product/${p.slug}`} className="quick-add">ELEGIR MODELO</Link></div></div></article>;
}

export function ProductGrid({list}:{list:Product[]}){return <div className="grid grid-cols-2 gap-x-3 gap-y-9 md:grid-cols-3 md:gap-x-5 lg:grid-cols-4">{list.map(p=><ProductCard p={p} key={p.slug}/>)}</div>}
export function DropClock(){return <div className="flex gap-5 font-display text-4xl md:text-6xl"><span>19<small className="ml-1 text-[9px] font-normal tracking-widest">D</small></span><span>08<small className="ml-1 text-[9px] font-normal tracking-widest">H</small></span><span>34<small className="ml-1 text-[9px] font-normal tracking-widest">M</small></span></div>}

export function Shop(){
  const {products,catalogLoading,catalogError}=useStore();const [query,setQuery]=useState('');const [filter,setFilter]=useState('TODO');
  const filters=['TODO','CASES','SMART','ACCESSORIES'];
  const filtered=products.filter(p=>(filter==='TODO'||p.category===filter)&&(p.name+p.collection+p.color+p.design+p.models.join(' ')).toLowerCase().includes(query.toLowerCase()));
  return <><Nav/><main className="light-page px-5 pb-24 pt-32 md:px-10"><div className="mb-10 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="eyebrow text-clay">CATÁLOGO / {products.length} DISEÑOS</p><h1 className="font-display mt-2 text-5xl tracking-tighter md:text-8xl">ENCUENTRA<br/>TU ESTILO</h1></div><label className="flex border-b border-black/25 pb-2"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Busca modelo, color o diseño" className="ml-2 w-64 bg-transparent text-sm outline-none placeholder:text-black/40"/></label></div><div className="mb-10 flex gap-2 overflow-auto">{filters.map(x=><button onClick={()=>setFilter(x)} className={`pill whitespace-nowrap ${filter===x?'active':''}`} key={x}>{x}</button>)}<button className="pill ml-auto"><SlidersHorizontal size={14}/></button></div>{catalogLoading?<p className="py-24 text-center text-muted">Cargando catálogo compatible…</p>:catalogError?<p className="mx-auto max-w-xl border border-clay/30 bg-white p-6 text-center text-clay">{catalogError}</p>:<ProductGrid list={filtered}/>} {!catalogLoading&&!catalogError&&!filtered.length&&<p className="py-24 text-center text-muted">No encontramos productos con esos filtros.</p>}</main></>;
}
